import { CelestialObject } from "./types";

// 距離定数（メートル）
const KM = 1e3;
const AU = 1.496e11;
const LY = 9.461e15;

export const CELESTIAL_OBJECTS: CelestialObject[] = [
  // ===== 地球圏 =====
  {
    id: "iss",
    name: "国際宇宙ステーション",
    nameEn: "ISS",
    ra: 0,
    dec: 0,
    distanceM: 408 * KM,
    type: "satellite",
    layer: "earth-orbit",
    description: "地上約408kmを周回する宇宙ステーション。90分で地球を1周する。",
    dynamic: true,
  },
  {
    id: "himawari",
    name: "ひまわり9号",
    nameEn: "Himawari-9",
    ra: 140.7,
    dec: 0,
    distanceM: 35786 * KM,
    type: "satellite",
    layer: "earth-orbit",
    description: "東経140.7度の静止軌道上にある気象観測衛星。",
  },

  // ===== 太陽系 =====
  {
    id: "moon",
    name: "月",
    nameEn: "Moon",
    ra: 0,
    dec: 0,
    distanceM: 3.844e8,
    type: "planet",
    layer: "solar-system",
    description: "地球唯一の天然衛星。距離約38.4万km。",
    magnitude: -12.7,
    dynamic: true,
  },
  {
    id: "sun",
    name: "太陽",
    nameEn: "Sun",
    ra: 0,
    dec: 0,
    distanceM: 1 * AU,
    type: "star",
    layer: "solar-system",
    description: "太陽系の中心。光が届くのに約8分19秒。",
    magnitude: -26.7,
    dynamic: true,
  },
  {
    id: "mercury",
    name: "水星",
    nameEn: "Mercury",
    ra: 0,
    dec: 0,
    distanceM: 0.39 * AU,
    type: "planet",
    layer: "solar-system",
    description: "太陽に最も近い惑星。公転周期88日。",
    magnitude: -0.4,
    dynamic: true,
  },
  {
    id: "venus",
    name: "金星",
    nameEn: "Venus",
    ra: 0,
    dec: 0,
    distanceM: 0.72 * AU,
    type: "planet",
    layer: "solar-system",
    description: "明けの明星・宵の明星として知られる。地球に最も近い惑星。",
    magnitude: -4.4,
    dynamic: true,
  },
  {
    id: "mars",
    name: "火星",
    nameEn: "Mars",
    ra: 0,
    dec: 0,
    distanceM: 1.52 * AU,
    type: "planet",
    layer: "solar-system",
    description: "赤く輝く惑星。将来の有人探査の最有力候補。",
    magnitude: -2.0,
    dynamic: true,
  },
  {
    id: "jupiter",
    name: "木星",
    nameEn: "Jupiter",
    ra: 0,
    dec: 0,
    distanceM: 5.20 * AU,
    type: "planet",
    layer: "solar-system",
    description: "太陽系最大の惑星。質量は地球の318倍。",
    magnitude: -2.7,
    dynamic: true,
  },
  {
    id: "saturn",
    name: "土星",
    nameEn: "Saturn",
    ra: 0,
    dec: 0,
    distanceM: 9.54 * AU,
    type: "planet",
    layer: "solar-system",
    description: "美しい環を持つ惑星。密度は水より低い。",
    magnitude: 0.4,
    dynamic: true,
  },
  {
    id: "uranus",
    name: "天王星",
    nameEn: "Uranus",
    ra: 0,
    dec: 0,
    distanceM: 19.19 * AU,
    type: "planet",
    layer: "solar-system",
    description: "自転軸が横倒しの氷の巨大惑星。",
    magnitude: 5.7,
    dynamic: true,
  },
  {
    id: "neptune",
    name: "海王星",
    nameEn: "Neptune",
    ra: 0,
    dec: 0,
    distanceM: 30.07 * AU,
    type: "planet",
    layer: "solar-system",
    description: "太陽系最遠の惑星。風速2000km/hの嵐が吹く。",
    magnitude: 7.8,
    dynamic: true,
  },

  // ===== 銀河 =====
  {
    id: "proxima-centauri",
    name: "プロキシマ・ケンタウリ",
    nameEn: "Proxima Centauri",
    ra: 217.43,
    dec: -62.68,
    distanceM: 4.24 * LY,
    type: "star",
    layer: "galaxy",
    description: "太陽から最も近い恒星。約4.2光年先。",
    magnitude: 11.1,
  },
  {
    id: "alpha-centauri",
    name: "アルファ・ケンタウリ",
    nameEn: "Alpha Centauri",
    ra: 219.90,
    dec: -60.83,
    distanceM: 4.37 * LY,
    type: "star",
    layer: "galaxy",
    description: "太陽に3番目に近い恒星系。肉眼でも見える。",
    magnitude: -0.27,
  },
  {
    id: "sirius",
    name: "シリウス",
    nameEn: "Sirius",
    ra: 101.29,
    dec: -16.72,
    distanceM: 8.6 * LY,
    type: "star",
    layer: "galaxy",
    description: "全天で最も明るい恒星。おおいぬ座の主星。",
    magnitude: -1.46,
  },
  {
    id: "vega",
    name: "ベガ（織姫星）",
    nameEn: "Vega",
    ra: 279.23,
    dec: 38.78,
    distanceM: 25 * LY,
    type: "star",
    layer: "galaxy",
    description: "こと座の主星。七夕の織姫星として有名。",
    magnitude: 0.03,
  },
  {
    id: "altair",
    name: "アルタイル（彦星）",
    nameEn: "Altair",
    ra: 297.70,
    dec: 8.87,
    distanceM: 16.7 * LY,
    type: "star",
    layer: "galaxy",
    description: "わし座の主星。七夕の彦星。",
    magnitude: 0.76,
  },
  {
    id: "deneb",
    name: "デネブ",
    nameEn: "Deneb",
    ra: 310.36,
    dec: 45.28,
    distanceM: 2615 * LY,
    type: "star",
    layer: "galaxy",
    description: "はくちょう座の主星。夏の大三角のひとつ。絶対光度が非常に高い。",
    magnitude: 1.25,
  },
  {
    id: "betelgeuse",
    name: "ベテルギウス",
    nameEn: "Betelgeuse",
    ra: 88.79,
    dec: 7.41,
    distanceM: 700 * LY,
    type: "star",
    layer: "galaxy",
    description: "オリオン座の赤色超巨星。近い将来、超新星爆発の可能性。",
    magnitude: 0.42,
  },
  {
    id: "polaris",
    name: "ポラリス（北極星）",
    nameEn: "Polaris",
    ra: 37.95,
    dec: 89.26,
    distanceM: 433 * LY,
    type: "star",
    layer: "galaxy",
    description: "現在の北極星。こぐま座の主星。",
    magnitude: 1.98,
  },
  {
    id: "orion-nebula",
    name: "オリオン大星雲",
    nameEn: "Orion Nebula (M42)",
    ra: 83.82,
    dec: -5.39,
    distanceM: 1344 * LY,
    type: "nebula",
    layer: "galaxy",
    description: "肉眼でも見える散光星雲。活発な星形成領域。",
    magnitude: 4.0,
  },
  {
    id: "crab-nebula",
    name: "かに星雲",
    nameEn: "Crab Nebula (M1)",
    ra: 83.63,
    dec: 22.01,
    distanceM: 6523 * LY,
    type: "nebula",
    layer: "galaxy",
    description: "1054年の超新星爆発の残骸。中心にパルサーがある。",
    magnitude: 8.4,
  },
  {
    id: "pleiades",
    name: "プレアデス星団（すばる）",
    nameEn: "Pleiades (M45)",
    ra: 56.75,
    dec: 24.12,
    distanceM: 444 * LY,
    type: "star-cluster",
    layer: "galaxy",
    description: "おうし座の散開星団。日本では「すばる」として知られる。",
    magnitude: 1.6,
  },
  {
    id: "galactic-center",
    name: "銀河中心（いて座A*）",
    nameEn: "Galactic Center (Sgr A*)",
    ra: 266.42,
    dec: -29.01,
    distanceM: 26000 * LY,
    type: "star",
    layer: "galaxy",
    description: "天の川銀河の中心。超大質量ブラックホールが存在する。",
  },
  {
    id: "omega-centauri",
    name: "オメガ星団",
    nameEn: "Omega Centauri",
    ra: 201.70,
    dec: -47.48,
    distanceM: 15800 * LY,
    type: "star-cluster",
    layer: "galaxy",
    description: "天の川銀河最大の球状星団。約1000万個の恒星を含む。",
    magnitude: 3.7,
  },

  // ===== 深宇宙 =====
  {
    id: "andromeda",
    name: "アンドロメダ銀河",
    nameEn: "Andromeda Galaxy (M31)",
    ra: 10.68,
    dec: 41.27,
    distanceM: 2.537e6 * LY,
    type: "galaxy",
    layer: "deep-universe",
    description: "天の川銀河の隣の大銀河。約250万光年先。肉眼で見える最も遠い天体。",
    magnitude: 3.4,
  },
  {
    id: "triangulum",
    name: "さんかく座銀河",
    nameEn: "Triangulum Galaxy (M33)",
    ra: 23.46,
    dec: 30.66,
    distanceM: 2.73e6 * LY,
    type: "galaxy",
    layer: "deep-universe",
    description: "局部銀河群で3番目に大きい渦巻銀河。",
    magnitude: 5.7,
  },
  {
    id: "lmc",
    name: "大マゼラン雲",
    nameEn: "Large Magellanic Cloud",
    ra: 80.89,
    dec: -69.76,
    distanceM: 1.58e5 * LY,
    type: "galaxy",
    layer: "deep-universe",
    description: "天の川銀河の伴銀河。南天で肉眼でも見える。",
    magnitude: 0.9,
  },
  {
    id: "smc",
    name: "小マゼラン雲",
    nameEn: "Small Magellanic Cloud",
    ra: 13.19,
    dec: -72.83,
    distanceM: 2.0e5 * LY,
    type: "galaxy",
    layer: "deep-universe",
    description: "大マゼラン雲と対をなす矮小銀河。",
    magnitude: 2.7,
  },
  {
    id: "virgo-cluster",
    name: "おとめ座銀河団",
    nameEn: "Virgo Cluster",
    ra: 187.71,
    dec: 12.39,
    distanceM: 5.4e7 * LY,
    type: "galaxy-cluster",
    layer: "deep-universe",
    description: "約1500個の銀河からなる銀河団。おとめ座超銀河団の中心。",
  },
  {
    id: "coma-cluster",
    name: "かみのけ座銀河団",
    nameEn: "Coma Cluster",
    ra: 194.95,
    dec: 27.98,
    distanceM: 3.21e8 * LY,
    type: "galaxy-cluster",
    layer: "deep-universe",
    description: "約1000個の銀河からなる巨大銀河団。",
  },
  {
    id: "3c273",
    name: "3C 273",
    nameEn: "Quasar 3C 273",
    ra: 187.28,
    dec: 2.05,
    distanceM: 2.44e9 * LY,
    type: "quasar",
    layer: "deep-universe",
    description: "最初に発見されたクエーサー。約24.4億光年先。",
    magnitude: 12.9,
  },
  {
    id: "ulas-j1342",
    name: "ULAS J1342+0928",
    nameEn: "ULAS J1342+0928",
    ra: 205.53,
    dec: 9.47,
    distanceM: 1.3e10 * LY,
    type: "quasar",
    layer: "deep-universe",
    description: "最も遠いクエーサーのひとつ。宇宙誕生から約7億年後の天体。",
  },
  {
    id: "cmb",
    name: "宇宙マイクロ波背景放射",
    nameEn: "Cosmic Microwave Background",
    ra: 0,
    dec: 0,
    distanceM: 4.4e26,
    type: "cmb",
    layer: "deep-universe",
    description: "観測可能な宇宙の端。ビッグバンから約38万年後に放たれた光。全方向に存在する。",
  },
];

export const LAYER_COLORS: Record<string, string> = {
  "earth-orbit": "#67d8ef",
  "solar-system": "#e6db74",
  galaxy: "#ae81ff",
  "deep-universe": "#f92672",
};

export const LAYER_NAMES: Record<string, string> = {
  "earth-orbit": "地球圏",
  "solar-system": "太陽系",
  galaxy: "銀河",
  "deep-universe": "深宇宙",
};
